backend:
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)

media_folder: 'static/img'
public_folder: '/img'

collections:
  - name: 'album'
    label: 'Album'
    folder: 'content/albums'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Album Link', name: 'link', widget: 'string' }
      - { label: 'Image', name: 'img', widget: 'image' }
  - name: 'resource'
    label: 'Resource'
    folder: 'content/resources'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Resources Link', name: 'link', widget: 'string' }
      - { label: 'Image', name: 'img', widget: 'image' }
  - name: 'monthposts'
    label: 'Month Posts'
    folder: 'content/monthposts'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Month', name: 'month', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'subheader', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'img', widget: 'image' }
  - name: 'eventpreview'
    label: 'Event Preveiw'
    folder: 'content/eventpreview'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Event Name', name: 'eventname', widget: 'string' }
      - { label: 'Event Month', name: 'eventmonth', widget: 'datetime' }
      - { label: 'Event Date', name: 'eventdate', widget: 'string' }
