backend:
  name: git-gateway
  branch: develop

media_folder: 'msksi/static/img/upload'
public_folder: '/img/upload'

collections:
  - name: 'album'
    label: 'Album'
    folder: 'msksi/content/albums'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Album Name', name: 'title', widget: 'string' }
      - { label: 'Album Link', name: 'link', widget: 'string' }
      - {
          label: 'Cover Image',
          name: 'img',
          widget: 'image',
          choose_url: false,
        }
  - name: 'resource'
    label: 'Resource'
    folder: 'msksi/content/resources'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Resource Name', name: 'title', widget: 'string' }
      - { label: 'Resources Link', name: 'link', widget: 'string' }
      - {
          label: 'Resource Image',
          name: 'img',
          widget: 'image',
          choose_url: false,
        }
  - name: 'monthposts'
    label: 'Month Posts'
    folder: 'msksi/content/monthposts'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Month', name: 'month', widget: 'string' }
      - { label: 'Post Title', name: 'subheader', widget: 'string' }
      - { label: 'Post Description', name: 'description', widget: 'string' }
      - { label: 'Post Image', name: 'img', widget: 'image', choose_url: false }

  - name: 'commspot'
    label: 'Community Spotlight'
    folder: 'msksi/content/commspot'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - {
          label: 'Title',
          name: 'title',
          widget: 'string',
          pattern:
            [
              '^.{5,25}$',
              'Must have more than 5 characters and less than 25 characters',
            ],
        }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          pattern:
            [
              '^.{10,120}$',
              'Must have more than 10 characters and less than 120 characters',
            ],
        }
      - { label: 'Main Image', name: 'img_main', widget: 'image' }
      - {
          label: 'Small Image 1',
          name: 'img_reel1',
          widget: 'image',
          choose_url: false,
        }
      - {
          label: 'Small Image 2',
          name: 'img_reel2',
          widget: 'image',
          choose_url: false,
        }
      - {
          label: 'Small Image 3',
          name: 'img_reel3',
          widget: 'image',
          choose_url: false,
        }
      - { label: 'Caption 1', name: 'reel_caption1', widget: 'string' }
      - { label: 'Caption 2', name: 'reel_caption2', widget: 'string' }
      - { label: 'Caption 3', name: 'reel_caption3', widget: 'string' }
